from sktime.classifiers.distance_based.elastic_ensemble import ElasticEnsemble
from sktime.classifiers.distance_based.proximity_forest import ProximityForest
from sktime.classifiers.distance_based.proximity_forest import ProximityStump
from sktime.classifiers.distance_based.proximity_forest import ProximityTree