# These are supported funding model platforms

github: sktime
patreon: # replace with username
open_collective: sktime
ko_fi: # replace with username
tidelift: # replace with username
community_bridge: # replace with username
liberapay: # replace with username
issuehunt: # replace with username
otechie: # replace with username
custom: https://gc-os-ai.github.io/donate
