# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# We need to build sktime before building the docs because otherwise Sphinx
#  cannot read the docstrings from Cython and C extension files
python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    # install doc requirements
    # - requirements: docs/requirements.txt
  build:
    os: ubuntu-20.04

sphinx:
  configuration: docs/source/conf.py
#  fail_on_warning: True
