"""Tests for all sktime forecasting metrics - probabilistic forecasts."""

import numpy as np
import pandas as pd

from sktime.tests.test_all_estimators import BaseFixtureGenerator, QuickTester
from sktime.utils._testing.series import _make_series


def _make_quantile_pred(y_true, alphas=(0.1, 0.5, 0.9)):
    """Make pred_quantiles DataFrame matching y_true index and columns."""
    if isinstance(y_true, pd.Series):
        y_true = y_true.to_frame()
    cols = pd.MultiIndex.from_product([y_true.columns, list(alphas)])
    data = np.random.uniform(0.8, 1.2, size=(len(y_true), len(cols)))
    return pd.DataFrame(data, index=y_true.index, columns=cols)


def _make_interval_pred(y_true, coverages=(0.9,)):
    """Make pred_interval DataFrame matching y_true index and columns."""
    if isinstance(y_true, pd.Series):
        y_true = y_true.to_frame()
    cols = pd.MultiIndex.from_product(
        [y_true.columns, list(coverages), ["lower", "upper"]]
    )
    data = np.random.uniform(0.8, 1.2, size=(len(y_true), len(cols)))
    return pd.DataFrame(data, index=y_true.index, columns=cols)


def _make_proba_pred(y_true):
    """Make pred_proba object (skpro distribution) matching y_true."""
    try:
        from skpro.distributions.normal import Normal
    except ImportError:
        return None
    if isinstance(y_true, pd.Series):
        y_true = y_true.to_frame()
    mu = pd.DataFrame(
        np.random.uniform(0.8, 1.2, size=y_true.shape),
        index=y_true.index,
        columns=y_true.columns,
    )
    sigma = pd.DataFrame(
        np.ones(y_true.shape),
        index=y_true.index,
        columns=y_true.columns,
    )
    return Normal(mu=mu, sigma=sigma)


def _make_pred(metric, y_true):
    """Make appropriate y_pred for the given metric based on scitype:y_pred tag."""
    pred_type = metric.get_tag("scitype:y_pred")
    if pred_type == "pred_quantiles":
        return _make_quantile_pred(y_true)
    elif pred_type == "pred_interval":
        return _make_interval_pred(y_true)
    elif pred_type == "pred_proba":
        return _make_proba_pred(y_true)
    return None


class ForecastingProbaMetricFixtureGenerator(BaseFixtureGenerator):
    """Fixture generator for probabilistic forecasting metric tests.

    Fixtures parameterized
    ----------------------
    estimator_class: estimator inheriting from BaseObject
        ranges over estimator classes not excluded by EXCLUDE_ESTIMATORS, EXCLUDED_TESTS
    estimator_instance: instance of estimator inheriting from BaseObject
        ranges over estimator classes not excluded by EXCLUDE_ESTIMATORS, EXCLUDED_TESTS
        instances are generated by create_test_instance class method
    scenario: instance of TestScenario
        ranges over all scenarios returned by retrieve_scenarios
    """

    estimator_type_filter = "metric_forecasting_proba"

    fixture_sequence = [
        "estimator_class",
        "estimator_instance",
        "fitted_estimator",
        "scenario",
    ]


class TestAllForecastingMetrics(ForecastingProbaMetricFixtureGenerator, QuickTester):
    """Module level tests for all sktime probabilistic forecast metrics."""

    def test_call_output(self, estimator_instance):
        """Test __call__ returns float or pd.Series based on score_average."""
        metric = estimator_instance
        y_true = _make_series(n_timepoints=20, random_state=42)
        y_pred = _make_pred(metric, y_true)
        if y_pred is None:
            return

        result = metric(y_true, y_pred)

        score_average = getattr(metric, "score_average", True)
        if score_average:
            assert isinstance(result, (float, np.floating)), (
                f"{type(metric).__name__}.__call__ with score_average=True "
                f"should return float, got {type(result)}"
            )
        else:
            assert isinstance(result, (float, np.floating, pd.Series)), (
                f"{type(metric).__name__}.__call__ should return "
                f"float or pd.Series, got {type(result)}"
            )

    def test_evaluate_by_index_output(self, estimator_instance):
        """Test evaluate_by_index returns pd.Series or pd.DataFrame."""
        metric = estimator_instance
        pred_type = metric.get_tag("scitype:y_pred")
        y_true = _make_series(n_timepoints=20, random_state=42)
        y_pred = _make_pred(metric, y_true)
        if y_pred is None:
            return

        result = metric.evaluate_by_index(y_true, y_pred)

        assert isinstance(result, (pd.Series, pd.DataFrame)), (
            f"{type(metric).__name__}.evaluate_by_index should return "
            f"pd.Series or pd.DataFrame, got {type(result)}"
        )

        if pred_type != "pred_proba":
            assert len(result) == len(y_true), (
                f"{type(metric).__name__}.evaluate_by_index length "
                f"should match y_true length for {pred_type}"
            )

    def test_call_equals_evaluate(self, estimator_instance):
        """Test __call__ gives same result as evaluate with matching multioutput."""
        metric = estimator_instance

        y_true = _make_series(n_timepoints=20, random_state=42)
        y_pred = _make_pred(metric, y_true)
        if y_pred is None:
            return

        np.random.seed(0)
        res_call = metric(y_true, y_pred)
        np.random.seed(0)
        res_eval = metric.evaluate(y_true, y_pred, multioutput=metric.multioutput)

        if isinstance(res_call, (float, np.floating)):
            assert np.isclose(res_call, float(res_eval)), (
                f"{type(metric).__name__}: __call__ and evaluate "
                f"should return equal values"
            )
        elif isinstance(res_call, pd.Series):
            pd.testing.assert_series_equal(res_call, res_eval)
