"""Tests for sktime detectors."""

__author__ = ["miraep8", "fkiraly", "klam-data", "pyyim", "mgorlin"]
__all__ = []

import pandas as pd
import pytest

from sktime.detection._datatypes._check import _is_valid_detection
from sktime.exceptions import NotFittedError
from sktime.tests.test_all_estimators import BaseFixtureGenerator, QuickTester
from sktime.utils._testing.detection import make_detection_problem
from sktime.utils._testing.hierarchical import _make_hierarchical
from sktime.utils.validation.detection import check_learning_type, check_task


def _make_pretrain_panel():
    """Make panel data for pretrain, 2 time series with 50 time points each."""
    return _make_hierarchical(
        hierarchy_levels=(2,), min_timepoints=50, max_timepoints=50
    )


class DetectorFixtureGenerator(BaseFixtureGenerator):
    """Fixture generator for time series detector (outlier, change point, etc) tests.

    Fixtures parameterized
    ----------------------
    object_class: estimator inheriting from BaseObject
        ranges over skbase classes not excluded by tests:skip_all/skip_by_name tags
    object_instance: instance of estimator inheriting from BaseObject
        ranges over skbase classes not excluded by tests:skip_all/skip_by_name tags
        instances are generated by create_test_instance class method
    scenario: instance of TestScenario
        ranges over all scenarios returned by retrieve_scenarios
    """

    # note: this should be separate from TestAllDetectors
    #   additional fixtures, parameters, etc should be added here
    #   TestAllDetectors should contain the tests only

    object_type_filter = "detector"

    fixture_sequence = [
        "object_class",
        "object_instance",
        "fitted_estimator",
        "scenario",
        "method_nsc",
        "method_nsc_arraylike",
    ]


class TestAllDetectors(DetectorFixtureGenerator, QuickTester):
    """Module level tests for all sktime detectors."""

    def test_output_type(self, object_instance):
        """Test detector output type."""
        estimator = object_instance

        X_train = make_detection_problem(
            n_timepoints=50, estimator_type=estimator.get_tag("distribution_type")
        )
        estimator.fit(X_train)
        X_test = make_detection_problem(
            n_timepoints=10, estimator_type=estimator.get_tag("distribution_type")
        )
        y_pred = estimator.predict(X_test)

        detector_type = estimator.get_tag("task")
        if detector_type in ["anomaly_detection", "change_point_detection"]:
            expected_y_pred_type = "points"
        elif detector_type == "segmentation":
            expected_y_pred_type = "segments"
        else:
            raise ValueError(
                f"Unknown task tag of {object_instance}: {detector_type}, "
                "expected one of ['anomaly_detection', 'change_point_detection', "
                f"'segmentation'], but found {detector_type}"
            )

        assert _is_valid_detection(y_pred, type=expected_y_pred_type), y_pred

    def test_transform_output_type(self, object_instance):
        """Test output type for the transform method."""
        X_train = make_detection_problem(
            n_timepoints=50,
            estimator_type=object_instance.get_tag("distribution_type"),
        )
        object_instance.fit(X_train)
        X_test = make_detection_problem(
            n_timepoints=10,
            estimator_type=object_instance.get_tag("distribution_type"),
        )
        y_test = object_instance.transform(X_test)
        assert isinstance(y_test, pd.DataFrame)
        assert len(y_test) == len(X_test)

    def test_predict_points(self, object_instance):
        X_train = make_detection_problem(
            n_timepoints=50,
            estimator_type=object_instance.get_tag("distribution_type"),
        )
        object_instance.fit(X_train)
        X_test = make_detection_problem(
            n_timepoints=10,
            estimator_type=object_instance.get_tag("distribution_type"),
        )
        y_pred = object_instance.predict_points(X_test)
        assert _is_valid_detection(y_pred, type="points"), y_pred

    def test_predict_segments(self, object_instance):
        X_train = make_detection_problem(
            n_timepoints=50,
            estimator_type=object_instance.get_tag("distribution_type"),
        )
        object_instance.fit(X_train)

        X_test = make_detection_problem(
            n_timepoints=10,
            estimator_type=object_instance.get_tag("distribution_type"),
        )
        y_pred = object_instance.predict_segments(X_test)
        assert _is_valid_detection(y_pred, type="segments"), y_pred

    def test_pretrain_then_fit_predict(self, object_instance):
        """Test pretrain can be called, and fit and predict work after it."""
        estimator = object_instance
        distribution_type = estimator.get_tag("distribution_type")

        estimator.pretrain(_make_pretrain_panel())
        assert estimator.state == "pretrained"

        X_train = make_detection_problem(
            n_timepoints=50, estimator_type=distribution_type
        )
        estimator.fit(X_train)
        assert estimator.state == "fitted"

        X_test = make_detection_problem(
            n_timepoints=10, estimator_type=distribution_type
        )
        # output format is checked in test_output_type, not here,
        # as some detectors skip that test
        y_pred = estimator.predict(X_test)
        assert isinstance(y_pred, pd.DataFrame)

    @pytest.mark.parametrize(
        "y", [None, pd.DataFrame({"ilocs": [3, 7]})], ids=["y_none", "y_events"]
    )
    def test_pretrain_is_noop(self, object_instance, y):
        """Test pretrain is callable, and stores nothing without the capability."""
        estimator = object_instance
        attrs_before = dict(vars(estimator))

        result = estimator.pretrain(_make_pretrain_panel(), y=y)

        assert result is estimator
        assert estimator.state == "pretrained"
        assert not estimator.is_fitted
        if not estimator.get_tag("capability:pretrain"):
            assert estimator.get_pretrained_params() == {}
            # nothing is stored, only the state changes
            assert vars(estimator).keys() == attrs_before.keys()
            unchanged = {k: v for k, v in attrs_before.items() if k != "_state"}
            assert all(vars(estimator)[k] is v for k, v in unchanged.items())

    def test_pretrain_state(self, object_instance):
        """Test the state moves to pretrained, then fitted, then pretrained again."""
        estimator = object_instance
        distribution_type = estimator.get_tag("distribution_type")
        X_train = make_detection_problem(
            n_timepoints=50, estimator_type=distribution_type
        )
        X_test = make_detection_problem(
            n_timepoints=10, estimator_type=distribution_type
        )

        estimator.pretrain(_make_pretrain_panel())
        assert estimator.state == "pretrained"
        assert not estimator.is_fitted
        with pytest.raises(NotFittedError):
            estimator.predict(X_test)

        estimator.fit(X_train)
        assert estimator.state == "fitted"
        assert estimator.is_fitted

        # as for forecasters, pretrain after fit sets the state to pretrained
        estimator.pretrain(_make_pretrain_panel())
        assert estimator.state == "pretrained"
        assert not estimator.is_fitted

    def test_pretrain_twice(self, object_instance):
        """Test a second pretrain call keeps the state, and stores nothing."""
        estimator = object_instance
        estimator.pretrain(_make_pretrain_panel())
        attrs_before = dict(vars(estimator))

        estimator.pretrain(_make_pretrain_panel())

        assert estimator.state == "pretrained"
        if not estimator.get_tag("capability:pretrain"):
            assert estimator.get_pretrained_params() == {}
            assert vars(estimator).keys() == attrs_before.keys()

    def test_clone_after_pretrain(self, object_instance):
        """Test clone after pretrain uses the pretrain clone plugin."""
        from sktime.forecasting.base._clone_plugin import _PretrainedCloner

        estimator = object_instance
        assert _PretrainedCloner in estimator._get_clone_plugins()

        estimator.pretrain(_make_pretrain_panel())
        estimator_clone = estimator.clone()

        assert estimator_clone is not estimator
        assert not estimator_clone.is_fitted
        assert estimator.state == "pretrained"
        if not estimator.get_tag("capability:pretrain"):
            assert estimator_clone.state == "new"
            assert estimator_clone.get_pretrained_params() == {}

    def test_detector_tags(self, object_class):
        """Check the learning_type and task tags are valid."""
        check_task(object_class.get_class_tag("task"))
        check_learning_type(object_class.get_class_tag("learning_type"))
