contact_links:
  - name: "\U0001F4AC All other questions and general chat"
    url: https://join.slack.com/t/sktime-group/shared_invite/zt-62i7aejn-vXc3nOWF26S_P3VXFPWisQ
    about: Chat with the sktime community on Slack
  - name: "\u2709\uFE0F Code of Conduct incident reporting"
    url: https://www.sktime.org/en/latest/code_of_conduct.html#incident-reporting-guidelines
    about: Report an incident to the Code of Conduct committee
