contact_links:
  - name: "\U0001F4AC All other questions and general chat"
    url: https://gitter.im/sktime/community
    about: Chat with the sktime community on Gitter
  - name: "\u2709\uFE0F Code of Conduct incident reporting"
    url: https://www.sktime.org/en/latest/code_of_conduct.html#incident-reporting-guidelines
    about: Report an incident to the Code of Conduct committee
