"""Golden-output regression tests for the PatchTST forecaster."""

import numpy as np
import pandas as pd
import pytest

from sktime.forecasting.patch_tst import PatchTSTForecaster
from sktime.tests.test_switch import run_test_for_class

_PATCHTST_MODEL = "ibm-granite/granite-timeseries-patchtst"
_CONTEXT_LENGTH = 512
_N_CHANNELS = 7

# Reference forecasts were generated by calling the transformers model class
# directly, bypassing sktime:
#
#   import numpy as np, torch
#   from transformers import PatchTSTForPrediction
#
#   model = PatchTSTForPrediction.from_pretrained(
#       "ibm-granite/granite-timeseries-patchtst"
#   )
#   model.eval()
#   y = np.random.RandomState(0).randn(512, 7).astype("float32")
#   with torch.no_grad():
#       out = model(past_values=torch.from_numpy(y).unsqueeze(0))
#   out.prediction_outputs[0].numpy()[:3, :3]
#
# ``load_airline`` is not usable here: this checkpoint is trained on ETTh1 and
# requires 7 input channels and a context length of 512, so a fixed-seed random
# array is used instead, as permitted by the issue.
_EXPECTED_HEAD = [
    [0.35354965925216675, 0.02547231689095497, 0.061923496425151825],
    [0.36408472061157227, -0.010364898480474949, 0.13800708949565887],
    [0.33699220418930054, -0.04303717985749245, 0.20896030962467194],
]


@pytest.mark.skipif(
    not run_test_for_class(PatchTSTForecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
def test_patch_tst_predictions_match_transformers_reference():
    """PatchTST zero-shot predictions match the raw transformers implementation."""
    values = np.random.RandomState(0).randn(_CONTEXT_LENGTH, _N_CHANNELS)
    columns = [f"c{i}" for i in range(_N_CHANNELS)]
    y = pd.DataFrame(values.astype("float32"), columns=columns)
    fh = list(range(1, 25))

    forecaster = PatchTSTForecaster(
        model_path=_PATCHTST_MODEL, fit_strategy="zero-shot"
    )
    y_pred = forecaster.fit(y, fh=fh).predict()

    np.testing.assert_allclose(
        y_pred.to_numpy()[:3, :3],
        np.asarray(_EXPECTED_HEAD, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )
