"""Regression tests for the Chronos and Chronos-Bolt forecaster."""

from types import SimpleNamespace

import numpy as np
import pytest
from skbase.utils.dependencies import _check_estimator_deps, _check_soft_dependencies

from sktime.datasets import load_airline
from sktime.forecasting.chronos import ChronosForecaster

if _check_soft_dependencies("torch", severity="none"):
    import torch

# Reference forecasts were generated by calling amazon-science/chronos-forecasting's
# ChronosPipeline/ChronosBoltPipeline directly, see scripts/golden-chronos.py.
#
# torch_dtype is forced to float32 (instead of the bfloat16 default) since
# bfloat16 has only ~3 significant decimal digits: cross-platform matmul
# reduction-order differences (x86 vs ARM, different thread counts) are large
# enough to occasionally flip which sample lands in a median/order-statistic,
# which is not a real implementation discrepancy but hardware-dependent noise.
_CHRONOS_REFERENCE_CASES = [
    pytest.param(
        "amazon/chronos-t5-tiny",
        {"seed": 0},
        [
            465.13885,
            383.83408,
            332.78226,
        ],
        id="chronos-t5-tiny-seed0-default-num-samples",
    ),
    pytest.param(
        "amazon/chronos-t5-tiny",
        {"seed": 42, "config": {"num_samples": 20}},
        [
            467.02966,
            386.6703,
            332.78226,
        ],
        id="chronos-t5-tiny-seed42-num-samples20",
    ),
    pytest.param(
        "amazon/chronos-bolt-tiny",
        {},
        [
            517.19104,
            432.6267,
            411.72766,
        ],
        id="chronos-bolt-tiny",
    ),
]


@pytest.mark.skipif(
    not _check_estimator_deps(ChronosForecaster, severity="none"),
    reason="run test only if ChronosForecaster soft dependencies are present",
)
@pytest.mark.parametrize(
    "model_path,forecaster_kwargs,expected_head",
    _CHRONOS_REFERENCE_CASES,
)
def test_chronos_airline_predictions_match_source_reference(
    model_path, forecaster_kwargs, expected_head
):
    """Chronos/Chronos-Bolt predictions match original outputs."""
    y = load_airline()
    fh = np.arange(1, 17)
    y_train = y.iloc[: -len(fh)]
    forecaster_kwargs = dict(forecaster_kwargs)
    config = {"torch_dtype": torch.float32, **forecaster_kwargs.pop("config", {})}
    forecaster = ChronosForecaster(
        model_path=model_path,
        use_source_package=False,
        config=config,
        **forecaster_kwargs,
    )

    y_pred = forecaster.fit(y_train, fh=fh).predict(fh=fh)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy().ravel(),
        np.asarray(expected_head, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )


class _FakeChronosBoltPipeline:
    """Minimal Chronos-Bolt pipeline stub for strategy tests.

    Avoids the heavy transformers/torch soft dependencies while still
    exercising ``ChronosBoltStrategy.predict`` logic.
    """

    def __init__(self, prediction_length=64):
        self.model = SimpleNamespace(
            config=SimpleNamespace(
                chronos_config={"prediction_length": prediction_length}
            )
        )
        self.last_call = None

    def predict(self, context, prediction_length, limit_prediction_length=False):
        self.last_call = (prediction_length, limit_prediction_length)

        class _TensorStub:
            def numpy(self):
                return np.zeros((1, prediction_length))

        return [_TensorStub()]


def test_chronos_bolt_predict_rejects_horizon_beyond_native_length():
    """Chronos-Bolt raises a clear error when fh exceeds native length (#11168)."""
    from sktime.forecasting.chronos import ChronosBoltStrategy

    pipeline = _FakeChronosBoltPipeline(prediction_length=64)
    strategy = ChronosBoltStrategy()
    config = strategy.initialize_config()

    with pytest.raises(ValueError, match="at most 64 steps"):
        strategy.predict(pipeline, None, 65, config)


def test_chronos_bolt_predict_within_native_length():
    """Chronos-Bolt predict works and forwards limit_prediction_length within limit."""
    from sktime.forecasting.chronos import ChronosBoltStrategy

    pipeline = _FakeChronosBoltPipeline(prediction_length=64)
    strategy = ChronosBoltStrategy()
    config = strategy.initialize_config()

    result = strategy.predict(pipeline, None, 16, config)

    assert result.shape == (16,)
    assert pipeline.last_call == (16, False)
