"""Tests for TimesFMForecaster.

TimesFmForecaster has a very restrictive dependency set,
which may cancel out with the matrix testing strategy.

Therefore, we call a check_estimator separately.
"""

# copyright: sktime developers, BSD-3-Clause License (see LICENSE file)

import numpy as np
import pytest

from sktime.datasets import load_airline
from sktime.forecasting.timesfm import TimesFMForecaster
from sktime.tests.test_switch import run_test_for_class
from sktime.utils import check_estimator

# Reference forecasts were generated by calling the upstream ``timesfm`` package
# directly, bypassing sktime (``timesfm==1.1.0``, the source of the vendored
# ``sktime.libs.timesfm``; the package requires Python 3.10 on Linux):
#
#   import numpy as np
#   import timesfm
#   from sktime.datasets import load_airline
#
#   y_train = load_airline().iloc[:-12]
#   tfm = timesfm.TimesFm(
#       context_len=160,  # TimesFMForecaster default: next multiple of 32 above 132
#       horizon_len=128,
#       input_patch_len=32,
#       output_patch_len=128,
#       num_layers=20,
#       model_dims=1280,
#       backend="cpu",
#   )
#   tfm.load_from_checkpoint(repo_id="google/timesfm-1.0-200m")
#   point_forecast, _ = tfm.forecast(np.expand_dims(y_train.values, axis=0))
#   point_forecast[0, :3]  # -> [401.70458984375, 392.5351257324219, 429.7332...]
_TIMESFM_EXPECTED_HEAD = [401.70458984375, 392.5351257324219, 429.7332458496094]


@pytest.mark.skipif(
    not run_test_for_class(TimesFMForecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
def test_timesfmforecaster():
    """Run standard test suite for TimesFMForecaster.

    TimesFmForecaster has a very restrictive dependency set,
    which may cancel out with the matrix testing strategy.

    Therefore, we call a check_estimator separately.
    """
    check_estimator(TimesFMForecaster, raise_exceptions=True)


@pytest.mark.skipif(
    not run_test_for_class(TimesFMForecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
def test_timesfm_airline_predictions_match_upstream_reference():
    """TimesFMForecaster predictions match the upstream ``timesfm`` implementation."""
    y_train = load_airline().iloc[:-12]
    fh = np.arange(1, 13)

    y_pred = TimesFMForecaster().fit(y_train, fh=fh).predict(fh=fh)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy(),
        np.asarray(_TIMESFM_EXPECTED_HEAD),
        rtol=1e-5,
        atol=1e-4,
    )
