"""Regression tests for the MomentFM forecaster."""

import numpy as np
import pytest
from skbase.utils.dependencies import _check_estimator_deps

from sktime.datasets import load_airline
from sktime.forecasting.momentfm import MomentFMForecaster

pytestmark = pytest.mark.skipif(
    not _check_estimator_deps(MomentFMForecaster, severity="none"),
    reason="skip test if required soft dependencies are not available",
)

# Reference forecast was generated by calling momentfm's MOMENTPipeline
# directly (momentfm==0.1.4), mirroring the windowing/padding/masking logic
# of MomentFMForecaster._fit/_predict.
#
# MomentFM has no zero-shot mode: the forecasting head is always randomly
# initialized and fine-tuned. To keep the reference reproducible across
# environments (independent of exactly how many RNG draws happen while
# loading the pretrained checkpoint, which depends on the installed
# transformers version), the head is overwritten with fixed, seeded weights
# after fit() and before predict(). This isolates the comparison to the
# forward-pass logic (padding, masking, normalization) that sktime is
# responsible for getting right.
_MOMENTFM_REFERENCE_HEAD = [
    355.5444030761719,
    293.86993408203125,
    358.5379638671875,
]


def _set_deterministic_head(model, seed=123):
    import torch

    g = torch.Generator().manual_seed(seed)
    w = model.head.linear.weight
    b = model.head.linear.bias
    with torch.no_grad():
        w.copy_(
            torch.empty(w.shape).normal_(mean=0.0, std=0.02, generator=g).to(w.device)
        )
        b.zero_()


def test_momentfm_airline_predictions_match_source_reference():
    """MomentFM predictions match the original momentfm pipeline outputs."""
    import torch

    y = load_airline()
    y_train = y.iloc[:-16]
    fh = np.arange(1, 17)

    torch.manual_seed(0)
    forecaster = MomentFMForecaster(
        pretrained_model_name_or_path="AutonLab/MOMENT-1-large",
        freeze_encoder=True,
        freeze_embedder=True,
        freeze_head=False,
        dropout=0.0,
        head_dropout=0.0,
        seq_len=64,
        batch_size=64,
        eval_batch_size=64,
        epochs=1,
        max_lr=1e-4,
        device="cpu",
        pct_start=0.3,
        max_norm=5.0,
        train_val_split=0.0,
    )
    forecaster.fit(y_train, fh=fh)
    _set_deterministic_head(forecaster.model)
    y_pred = forecaster.predict(fh=fh)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy().ravel(),
        np.asarray(_MOMENTFM_REFERENCE_HEAD, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )
