"""Tests for HFTransformersForecaster."""

__author__ = ["Spinachboul", "geetu040"]

import numpy as np
import pandas as pd
import pytest

from sktime.datasets import load_airline
from sktime.forecasting.hf_transformers import HFTransformersForecaster
from sktime.tests.test_switch import run_test_for_class


@pytest.mark.skipif(
    not run_test_for_class(HFTransformersForecaster),
    reason="Run test only if soft dependencies are present and incrementally",
)
def test_initialized_model():
    """Test passing an initialized model to HFTransformersForecaster."""
    from transformers import AutoformerConfig, AutoformerForPrediction

    # Define model configuration
    config = AutoformerConfig(
        num_dynamic_real_features=0,
        num_static_real_features=0,
        num_static_categorical_features=0,
        num_time_features=0,
        context_length=32,
        prediction_length=8,
        lags_sequence=[1, 2, 3],
    )

    # Initialize the model
    model = AutoformerForPrediction(config)

    # Initialize the forecaster with the model
    forecaster = HFTransformersForecaster(
        model_path=model,
        fit_strategy="minimal",
        training_args={
            "num_train_epochs": 1,
            "output_dir": "test_output",
            "per_device_train_batch_size": 4,
        },
    )

    # Load dataset
    y = load_airline()

    # Fit the model
    forecaster.fit(y)

    # Define the forecasting horizon and predict
    fh = [1, 2, 3]
    y_pred = forecaster.predict(fh)

    # Assertions
    assert y_pred is not None
    assert len(y_pred) == len(fh)


# Reference forecasts were generated by calling the model's `*ForPrediction`
# class and `.generate(...)` directly, bypassing sktime entirely.
#
# These checkpoints are used rather than `huggingface/*-tourism-monthly` because
# they were pretrained without static-categorical features, which the forecaster
# does not support and always zeroes out. Passing exogenous features (`X`) with
# exactly `config.num_time_features` columns then reproduces each checkpoint's
# architecture exactly, so no layer is reinitialized and no parameter is
# trainable -- fitting is a no-op and prediction is genuinely zero-shot.
_HF_TRAFFIC_HOURLY_REFERENCE_CASES = [
    pytest.param(
        "kashif/informer-traffic-hourly",
        [1577.8319, 482.05606, 707.55133],
        id="informer-traffic-hourly",
    ),
    pytest.param(
        "kashif/autoformer-traffic-hourly",
        [211.2461, 17.348618, 24.003185],
        id="autoformer-traffic-hourly",
    ),
    pytest.param(
        "kashif/time-series-transformer-traffic-hourly",
        [740.9819, 635.026, 579.87787],
        id="time-series-transformer-traffic-hourly",
    ),
]


@pytest.mark.skipif(
    not run_test_for_class(HFTransformersForecaster),
    reason="Run test only if soft dependencies are present and incrementally",
)
@pytest.mark.parametrize(
    "model_path,expected_head",
    _HF_TRAFFIC_HOURLY_REFERENCE_CASES,
)
def test_hf_transformers_zero_shot_matches_source_reference(model_path, expected_head):
    """Zero-shot predictions match the original transformers implementation."""
    from transformers import AutoConfig

    config = AutoConfig.from_pretrained(model_path)
    ntf = config.num_time_features
    fh_len = config.prediction_length

    n = 1000
    t = np.arange(n)
    y = pd.Series(np.arange(1, n + 1, dtype="float32"))
    X = pd.DataFrame(
        {f"f{i}": ((t + i) % (7 + i)) / (7 + i) for i in range(ntf)}, index=y.index
    )
    fh = list(range(1, fh_len + 1))
    t_future = np.arange(n, n + fh_len)
    X_future = pd.DataFrame(
        {f"f{i}": ((t_future + i) % (7 + i)) / (7 + i) for i in range(ntf)},
        index=range(n, n + fh_len),
    )

    forecaster = HFTransformersForecaster(
        model_path=model_path,
        fit_strategy="minimal",
        validation_split=None,
        training_args={
            "num_train_epochs": 1,
            "output_dir": "test_output",
            "per_device_train_batch_size": 32,
            "disable_tqdm": True,
            "report_to": "none",
            "use_cpu": True,
        },
        deterministic=True,
    )
    forecaster.fit(y, X=X, fh=fh)

    # a genuinely zero-shot forecast has no reinitialized weights to adapt
    assert not forecaster.info["mismatched_keys"]
    assert not any(p.requires_grad for p in forecaster.model.parameters())

    y_pred = forecaster.predict(fh=fh, X=X_future)

    np.testing.assert_allclose(
        y_pred.to_numpy()[:3],
        np.asarray(expected_head, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )
