"""Tests for Chronos2Forecaster."""

import numpy as np
import pandas as pd
import pytest
from skbase.utils.dependencies import _check_estimator_deps

from sktime.datasets import load_airline
from sktime.forecasting.chronos2 import Chronos2Forecaster


@pytest.mark.skipif(
    not _check_estimator_deps(Chronos2Forecaster, severity="none"),
    reason="autots not available",
)
def test_chronos2_fit_truncates_context_on_time_axis():
    """`context_length` truncation should apply to time axis, not feature axis."""
    pytest.importorskip("torch")

    y = pd.DataFrame(np.arange(300).reshape(100, 3), columns=["a", "b", "c"])
    forecaster = Chronos2Forecaster(config={"context_length": 10}, ignore_deps=True)
    forecaster._load_pipeline = lambda: object()

    forecaster._fit(y)

    assert forecaster._context.shape == (3, 10)


def test_chronos2_update_rebuilds_truncated_context():
    """``_update`` appends new data and keeps only ``context_length`` history.

    Chronos-2 is zero-shot: prediction reads ``self._context``, so update must
    rebuild that window rather than refitting or leaving a stale context.
    """
    pytest.importorskip("torch")

    y = pd.DataFrame({"a": np.arange(20, dtype=np.float64)})
    forecaster = Chronos2Forecaster(config={"context_length": 4}, ignore_deps=True)
    forecaster._load_pipeline = lambda: object()
    forecaster._fit(y)

    y_new = pd.DataFrame(
        {"a": np.arange(20, 25, dtype=np.float64)}, index=pd.RangeIndex(20, 25)
    )
    forecaster._update(y_new)

    assert forecaster._context.shape == (1, 4)
    np.testing.assert_array_equal(forecaster._context[0], [21, 22, 23, 24])
    np.testing.assert_array_equal(
        forecaster._cur_y["a"].to_numpy(), [21, 22, 23, 24]
    )


def test_chronos2_update_refreshes_context_via_public_api():
    """Public ``update`` refreshes ``_context`` even with ``update_params=False``."""
    pytest.importorskip("torch")

    y = pd.DataFrame({"a": np.arange(10, dtype=np.float64)})
    forecaster = Chronos2Forecaster(config={"context_length": 5}, ignore_deps=True)
    forecaster._load_pipeline = lambda: object()
    forecaster.fit(y, fh=1)

    y_new = pd.DataFrame(
        {"a": np.arange(10, 14, dtype=np.float64)}, index=pd.RangeIndex(10, 14)
    )
    forecaster.update(y_new, update_params=False)

    assert forecaster._context.shape == (1, 5)
    np.testing.assert_array_equal(forecaster._context[0], [9, 10, 11, 12, 13])
    assert len(forecaster._y) == 5
    np.testing.assert_array_equal(forecaster._y["a"].to_numpy(), [9, 10, 11, 12, 13])


def test_chronos2_update_trims_past_covariates_with_context():
    """Past covariates in ``_cur_X`` are trimmed to the same context window."""
    pytest.importorskip("torch")

    y = pd.DataFrame({"a": np.arange(12, dtype=np.float64)})
    X = pd.DataFrame({"cov": np.arange(100, 112, dtype=np.float64)})
    forecaster = Chronos2Forecaster(config={"context_length": 4}, ignore_deps=True)
    forecaster._load_pipeline = lambda: object()
    forecaster._fit(y, X=X)

    y_new = pd.DataFrame(
        {"a": np.arange(12, 15, dtype=np.float64)}, index=pd.RangeIndex(12, 15)
    )
    X_new = pd.DataFrame(
        {"cov": np.arange(112, 115, dtype=np.float64)}, index=pd.RangeIndex(12, 15)
    )
    forecaster._update(y_new, X=X_new)

    assert len(forecaster._cur_y) == 4
    assert len(forecaster._cur_X) == 4
    np.testing.assert_array_equal(
        forecaster._cur_y["a"].to_numpy(), [11, 12, 13, 14]
    )
    np.testing.assert_array_equal(
        forecaster._cur_X["cov"].to_numpy(), [111, 112, 113, 114]
    )
    assert forecaster._context.shape == (1, 4)


# Reference forecasts were generated by calling chronos.Chronos2Pipeline directly
# (chronos-forecasting v2.3.1), bypassing sktime entirely. See the PR description
# for the exact script used to produce these values.
#
# torch_dtype is pinned to float32 (rather than the forecaster's bfloat16
# default) because bfloat16 CPU matmul/attention reductions are not
# bit-reproducible across BLAS backends (e.g. Linux OpenBLAS/MKL vs. macOS
# Accelerate), which was observed to fail CI on macos-latest while passing on
# Linux. float32 has enough mantissa precision to keep cross-platform
# rounding differences well under the assertion tolerance.
_CHRONOS2_AIRLINE_REFERENCE_CASES = [
    pytest.param(
        "amazon/chronos-2",
        None,
        [489.13516, 424.1904, 349.09723],
        id="chronos-2-full-context",
    ),
    pytest.param(
        "autogluon/chronos-2-small",
        None,
        [477.62878, 413.4264, 352.4988],
        id="chronos-2-small-full-context",
    ),
    pytest.param(
        "amazon/chronos-2",
        50,
        [464.2062, 395.73822, 339.5051],
        id="chronos-2-truncated-context",
    ),
]


@pytest.mark.skipif(
    not _check_estimator_deps(Chronos2Forecaster, severity="none"),
    reason="Chronos2Forecaster soft dependencies not available",
)
@pytest.mark.parametrize(
    "model_path,context_length,expected_head",
    _CHRONOS2_AIRLINE_REFERENCE_CASES,
)
def test_chronos2_airline_predictions_match_source_reference(
    model_path, context_length, expected_head
):
    """Chronos-2 predictions match the original Chronos2Pipeline outputs."""
    import torch

    y = load_airline()
    y_train = y.iloc[:-16]
    fh = np.arange(1, 17)
    forecaster = Chronos2Forecaster(
        model_path=model_path,
        config={
            "device_map": "cpu",
            "context_length": context_length,
            "torch_dtype": torch.float32,
        },
        seed=1,
    )

    y_pred = forecaster.fit(y_train, fh=fh).predict(fh=fh)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy().flatten(),
        np.asarray(expected_head, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )


@pytest.mark.skipif(
    not _check_estimator_deps(Chronos2Forecaster, severity="none"),
    reason="Chronos2Forecaster soft dependencies not available",
)
def test_chronos2_multivariate_cross_learning_matches_source_reference():
    """Multivariate cross-learning predictions match the source implementation."""
    import torch

    rng = np.random.default_rng(0)
    n_vars, T, prediction_length = 3, 100, 12
    target = rng.standard_normal((n_vars, T)).astype(np.float32)
    y = pd.DataFrame(target.T, columns=["a", "b", "c"])

    forecaster = Chronos2Forecaster(
        model_path="amazon/chronos-2",
        config={
            "device_map": "cpu",
            "cross_learning": True,
            "torch_dtype": torch.float32,
        },
        seed=1,
    )
    fh = np.arange(1, prediction_length + 1)
    y_pred = forecaster.fit(y, fh=fh).predict(fh=fh)

    expected_head = np.asarray(
        [
            [0.01415852, 0.04798034, 0.05568328],
            [-0.02250395, -0.01932248, -0.03341879],
            [-0.15492375, -0.15401685, -0.16102317],
        ],
        dtype=np.float32,
    ).T

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy(),
        expected_head,
        rtol=1e-5,
        atol=1e-4,
    )


@pytest.mark.skipif(
    not _check_estimator_deps(Chronos2Forecaster, severity="none"),
    reason="Chronos2Forecaster soft dependencies not available",
)
def test_chronos2_covariates_match_source_reference():
    """Predictions with past/future covariates match the source implementation."""
    import torch

    rng = np.random.default_rng(1)
    T, prediction_length = 80, 8
    target = rng.standard_normal(T).astype(np.float32)
    past_cov1 = rng.standard_normal(T).astype(np.float32)
    past_cov2 = rng.standard_normal(T).astype(np.float32)
    future_cov1 = rng.standard_normal(prediction_length).astype(np.float32)

    y = pd.DataFrame({"target": target})
    X_train = pd.DataFrame({"cov1": past_cov1, "cov2": past_cov2})
    X_future = pd.DataFrame({"cov1": future_cov1})
    X_future.index = range(T, T + prediction_length)

    forecaster = Chronos2Forecaster(
        model_path="amazon/chronos-2",
        config={"device_map": "cpu", "torch_dtype": torch.float32},
        seed=1,
    )
    fh = np.arange(1, prediction_length + 1)
    forecaster.fit(y, X=X_train, fh=fh)
    y_pred = forecaster.predict(fh=fh, X=X_future)

    expected_head = np.asarray([-0.10913494, -0.11017366, -0.1326932], dtype=np.float32)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy().flatten(),
        expected_head,
        rtol=1e-5,
        atol=1e-4,
    )
