"""Regression tests for the TimesFM-3 forecaster."""

import numpy as np
import pandas as pd
import pytest

from sktime.datasets import load_airline
from sktime.forecasting.timesfm3 import TimesFM3Forecaster
from sktime.tests.test_switch import run_test_for_class

# Reference forecasts were generated by calling timesfm3.TimesFM3Evaluator directly
# (bypassing sktime), e.g.:
#
#   from timesfm3 import TimesFM3Evaluator, ModelConfig
#   from sktime.datasets import load_airline
#
#   y_train = load_airline().iloc[:-12]
#   config = ModelConfig(
#       checkpoint_path="google/timesfm-3.0-pytorch",
#       per_core_batch_size=1,
#       device="cpu",
#   )
#   model = TimesFM3Evaluator(config)
#   ctx = y_train.values.astype(np.float32)
#   out = list(
#       model.predict_batch(
#           [ctx],
#           horizon=12,
#           return_quantiles=True,
#           use_symmetric_averaging=False,
#           make_positive=False,
#       )
#   )[0]
#   out.forecast[:3]
_TIMESFM3_COMMON_KWARGS = {
    "checkpoint_path": "google/timesfm-3.0-pytorch",
    "device": "cpu",
    "per_core_batch_size": 1,
    "predict_kwargs": {
        "use_symmetric_averaging": False,
        "make_positive": False,
    },
}


@pytest.mark.skipif(
    not run_test_for_class(TimesFM3Forecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
def test_timesfm3_airline_predictions_match_upstream_reference():
    """TimesFM-3 univariate predictions match the upstream evaluator."""
    y = load_airline()
    y_train = y.iloc[:-12]
    fh = np.arange(1, 13)

    forecaster = TimesFM3Forecaster(**_TIMESFM3_COMMON_KWARGS)
    y_pred = forecaster.fit(y_train, fh=fh).predict(fh=fh)

    expected_head = np.asarray(
        [418.6312, 399.61554, 462.08493],
        dtype=np.float32,
    )
    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy(),
        expected_head,
        rtol=1e-5,
        atol=1e-4,
    )


@pytest.mark.skipif(
    not run_test_for_class(TimesFM3Forecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
def test_timesfm3_multivariate_predictions_match_upstream_reference():
    """TimesFM-3 multivariate predictions match the upstream evaluator."""
    from timesfm3 import ModelConfig, TimesFM3Evaluator

    rng = np.random.default_rng(0)
    context_len, horizon = 128, 8
    target = rng.standard_normal((3, context_len)).astype(np.float32)
    y = pd.DataFrame(target.T, columns=["a", "b", "c"])

    upstream = TimesFM3Evaluator(
        ModelConfig(
            checkpoint_path="google/timesfm-3.0-pytorch",
            per_core_batch_size=1,
            device="cpu",
        )
    )
    expected = list(
        upstream.predict_batch(
            [target],
            horizon=horizon,
            return_quantiles=False,
            use_symmetric_averaging=False,
            make_positive=False,
        )
    )[0].forecast

    forecaster = TimesFM3Forecaster(**_TIMESFM3_COMMON_KWARGS)
    fh = np.arange(1, horizon + 1)
    y_pred = forecaster.fit(y, fh=fh).predict(fh=fh)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy(),
        expected[:, :3].T,
        rtol=1e-5,
        atol=1e-4,
    )


@pytest.mark.skipif(
    not run_test_for_class(TimesFM3Forecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
def test_timesfm3_covariates_match_upstream_reference():
    """TimesFM-3 predictions with covariates match the upstream evaluator."""
    from timesfm3 import ModelConfig, TimesFM3Evaluator

    rng = np.random.default_rng(1)
    context_len, horizon = 128, 8
    target = rng.standard_normal((2, context_len)).astype(np.float32)
    past_only = rng.standard_normal((1, context_len)).astype(np.float32)
    past_future = rng.standard_normal((1, context_len + horizon)).astype(np.float32)

    upstream = TimesFM3Evaluator(
        ModelConfig(
            checkpoint_path="google/timesfm-3.0-pytorch",
            per_core_batch_size=1,
            device="cpu",
        )
    )
    expected = list(
        upstream.predict_batch(
            [target],
            horizon=horizon,
            past_only_covariates=[past_only],
            past_future_covariates=[past_future],
            return_quantiles=False,
            use_symmetric_averaging=False,
            make_positive=False,
        )
    )[0].forecast

    y = pd.DataFrame(target.T, columns=["y1", "y2"])
    index = pd.RangeIndex(context_len)
    X_train = pd.DataFrame(
        {
            "po": past_only.ravel(),
            "pf": past_future[:, :context_len].ravel(),
        },
        index=index,
    )
    X_future = pd.DataFrame(
        {"pf": past_future[:, context_len : context_len + horizon].ravel()},
        index=range(context_len, context_len + horizon),
    )

    forecaster = TimesFM3Forecaster(
        **_TIMESFM3_COMMON_KWARGS,
        past_only_covariate_cols=["po"],
    )
    fh = np.arange(1, horizon + 1)
    y_pred = forecaster.fit(y, X=X_train, fh=fh).predict(fh=fh, X=X_future)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy(),
        expected[:, :3].T,
        rtol=1e-5,
        atol=1e-4,
    )


def test_timesfm3_covariate_column_resolution():
    """Past-only vs past-future covariate columns are resolved without model load."""
    forecaster = TimesFM3Forecaster(ignore_deps=True)
    forecaster._X = pd.DataFrame({"po": [1.0], "pf": [2.0]})
    past_only, past_future = forecaster._resolve_covariate_columns(
        pd.DataFrame({"pf": [3.0]})
    )
    assert past_only == ["po"]
    assert past_future == ["pf"]
