"""Regression tests for the MOIRAI forecaster."""

import numpy as np
import pytest
from skbase.utils.dependencies import _check_estimator_deps

from sktime.datasets import load_airline
from sktime.forecasting.moirai import MOIRAIForecaster

# Reference forecasts were generated by uni2ts's MoiraiForecast/MoiraiModule,
# called directly (not through sktime), following the "Getting Started" example
# in the uni2ts README (https://github.com/SalesforceAIResearch/uni2ts).
_MOIRAI_REFERENCE_CASES = [
    pytest.param(
        "Salesforce/moirai-1.0-R-small",
        [
            510.054443359,
            485.214874268,
            462.110443115,
        ],
        id="salesforce-checkpoint",
    ),
    pytest.param(
        "sktime/moirai-1.0-R-small",
        [
            527.526184082,
            502.378295898,
            484.770690918,
        ],
        id="sktime-checkpoint",
    ),
]


@pytest.mark.skipif(
    not _check_estimator_deps(MOIRAIForecaster, severity="none"),
    reason="run test only if MOIRAIForecaster soft dependencies are present",
)
@pytest.mark.parametrize(
    "checkpoint_path,expected_head",
    _MOIRAI_REFERENCE_CASES,
)
def test_moirai_airline_predictions_match_uni2ts_reference(
    checkpoint_path, expected_head
):
    """MOIRAI predictions match the original uni2ts MoiraiForecast pipeline."""
    y = load_airline()
    y_train = y.iloc[:-16]
    fh = np.arange(1, 17)
    forecaster = MOIRAIForecaster(
        checkpoint_path=checkpoint_path,
        deterministic=True,
        use_source_package=False,
    )

    y_pred = forecaster.fit(y_train, fh=fh).predict(fh=fh)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy(),
        np.asarray(expected_head, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )
