"""Golden-output regression tests for the TimesFM 3 forecaster.

Interface conformance (shapes, index, dtypes, tags, pickle, ...) is covered by
``check_estimator``. The tests here validate the full sktime pipeline end-to-end
against reference outputs generated by calling the upstream ``timesfm3`` package
directly (see ``scripts/golden-timesfm3.py`` and issue #10672), and check that
``predict_proba`` is consistent with ``predict_quantiles`` (#10566).

The ``EXPECTED_*`` constants below are the committed reference values. Regenerate
them on a machine with ``timesfm[torch]`` and the ``google/timesfm-3.0-pytorch``
checkpoint::

    python scripts/golden-timesfm3.py

and paste the printed arrays here if the upstream model or preprocessing changes.
Inference is pinned to ``device="cpu"`` for reproducibility.
"""

from __future__ import annotations

import numpy as np
import pytest

from sktime.datasets import load_airline
from sktime.forecasting.timesfm3 import TimesFM3Forecaster
from sktime.tests.test_switch import run_test_for_class

# Golden references generated against the `google/timesfm-3.0-pytorch` checkpoint on CPU
EXPECTED_AIRLINE = [418.6311950683594, 399.6155700683594, 462.0848693847656]
EXPECTED_COV = [
    [-0.7916899919509888, 0.22182999551296234],
    [-0.7092300057411194, 0.15444999933242798],
]


@pytest.mark.skipif(
    not run_test_for_class(TimesFM3Forecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
def test_timesfm3_airline_matches_source_reference():
    """Univariate point forecast matches upstream reference on ``load_airline``."""
    y_train = load_airline().iloc[:-12]

    forecaster = TimesFM3Forecaster(device="cpu", license_accepted=True)
    forecaster.fit(y_train)
    y_pred = forecaster.predict(fh=[1, 2, 3])

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy().ravel(),
        np.asarray(EXPECTED_AIRLINE, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )


@pytest.mark.skipif(
    not run_test_for_class(TimesFM3Forecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
def test_timesfm3_covariates_match_source_reference():
    """Multivariate + mixed covariate forecast matches the upstream reference.

    The covariate split is inferred: ``past_only`` is supplied only in fit-time
    ``X`` (past-only), while ``future_known`` is in both the fit-time and
    predict-time ``X`` (past-and-future). Data is drawn with a fixed seed and in
    the same order as ``scripts/golden-timesfm3.py``.
    """
    import pandas as pd

    rng = np.random.default_rng(0)
    n, horizon = 32, 4
    ta = rng.normal(size=n)
    tb = rng.normal(size=n)
    po = rng.normal(size=n)
    fk = rng.normal(size=n)
    fkf = rng.normal(size=horizon)

    y = pd.DataFrame({"target_a": ta, "target_b": tb})
    X = pd.DataFrame({"past_only": po, "future_known": fk})
    X_future = pd.DataFrame({"future_known": fkf})

    forecaster = TimesFM3Forecaster(device="cpu", license_accepted=True)
    forecaster.fit(y, X=X)
    y_pred = forecaster.predict(fh=list(range(1, horizon + 1)), X=X_future)

    np.testing.assert_allclose(
        y_pred.iloc[:2].to_numpy(),
        np.asarray(EXPECTED_COV, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )


@pytest.mark.skipif(
    not run_test_for_class(TimesFM3Forecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
def test_timesfm3_predict_proba_matches_quantiles():
    """``predict_proba().quantile`` agrees with ``predict_quantiles`` (#10566)."""
    y_train = load_airline().iloc[:-12]
    fh = [1, 2, 3]
    alpha = [0.1, 0.25, 0.5, 0.9]

    forecaster = TimesFM3Forecaster(device="cpu", license_accepted=True)
    forecaster.fit(y_train)

    q_direct = forecaster.predict_quantiles(fh=fh, alpha=alpha)
    q_proba = forecaster.predict_proba(fh=fh).quantile(alpha=alpha)

    np.testing.assert_allclose(
        q_direct.to_numpy(), q_proba.to_numpy(), rtol=1e-5, atol=1e-4
    )
