"""Regression tests for the Toto (v1) forecaster."""

import numpy as np
import pandas as pd
import pytest
from skbase.utils.dependencies import _check_estimator_deps

from sktime.datasets import load_airline
from sktime.forecasting.toto import TotoForecaster

# Reference forecasts were generated by calling
# toto.inference.forecaster.TotoForecaster.forecast() directly (toto-ts>=0.1.3)
_TOTO_AIRLINE_REFERENCE_CASES = [
    pytest.param(
        {"prediction_type": "mean", "num_samples": None},
        [488.28717, 417.58038, 376.97644],
        id="mean-num_samples-None",
    ),
    pytest.param(
        {"prediction_type": "median", "num_samples": 1, "samples_per_batch": 1},
        [438.4101, 396.69385, 376.97928],
        id="median-num_samples-1",
    ),
    pytest.param(
        {"prediction_type": "mean", "num_samples": 2, "samples_per_batch": 2},
        [461.18848, 469.096, 376.23752],
        id="mean-num_samples-2",
    ),
]


@pytest.mark.skipif(
    not _check_estimator_deps(TotoForecaster, severity="none"),
    reason="run test only if TotoForecaster soft dependencies are present",
)
@pytest.mark.parametrize(
    "forecaster_kwargs,expected_head",
    _TOTO_AIRLINE_REFERENCE_CASES,
)
def test_toto_airline_predictions_match_source_reference(
    forecaster_kwargs, expected_head
):
    """Toto predictions match the original toto.inference.forecaster output."""
    y = load_airline()
    y_train = y.iloc[:-16]
    fh = np.arange(1, 17)
    forecaster = TotoForecaster(
        model_path="Datadog/Toto-Open-Base-1.0",
        device="cpu",
        seed=0,
        **forecaster_kwargs,
    )

    y_pred = forecaster.fit(y_train, fh=fh).predict(fh=fh)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy().flatten(),
        np.asarray(expected_head, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )


@pytest.mark.skipif(
    not _check_estimator_deps(TotoForecaster, severity="none"),
    reason="run test only if TotoForecaster soft dependencies are present",
)
def test_toto_exogenous_predictions_match_source_reference():
    """Toto predictions with known-future exogenous X match source output."""
    rng = np.random.default_rng(0)
    context_len, prediction_length = 60, 8
    target = rng.standard_normal(context_len).astype(np.float32)
    exog1 = rng.standard_normal(context_len).astype(np.float32)
    future_exog1 = rng.standard_normal(prediction_length).astype(np.float32)

    idx = pd.RangeIndex(context_len)
    y = pd.DataFrame({"target": target}, index=idx)
    X = pd.DataFrame({"exog1": exog1}, index=idx)
    future_idx = pd.RangeIndex(context_len, context_len + prediction_length)
    X_future = pd.DataFrame({"exog1": future_exog1}, index=future_idx)

    forecaster = TotoForecaster(
        model_path="Datadog/Toto-Open-Base-1.0",
        device="cpu",
        seed=0,
        num_samples=None,
        prediction_type="mean",
    )
    fh = np.arange(1, prediction_length + 1)
    y_pred = forecaster.fit(y, X=X, fh=fh).predict(fh=fh, X=X_future)

    expected_head = np.asarray([0.08084736, 0.08218868, 0.04493088], dtype=np.float32)
    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy().flatten(),
        expected_head,
        rtol=1e-5,
        atol=1e-4,
    )


@pytest.mark.skipif(
    not _check_estimator_deps(TotoForecaster, severity="none"),
    reason="run test only if TotoForecaster soft dependencies are present",
)
def test_toto_predict_proba_returns_empirical_samples():
    """Toto's empirical distribution preserves samples and forecast axes."""
    from skpro.distributions.empirical import Empirical

    y = load_airline()
    y_train = y.iloc[:-16]
    fh = np.array([1, 3, 5])
    forecaster = TotoForecaster(
        model_path="Datadog/Toto-Open-Base-1.0",
        device="cpu",
        seed=0,
        num_samples=9,
        samples_per_batch=9,
    ).fit(y_train, fh=fh)

    pred_dist = forecaster.predict_proba(fh=fh, marginal=False)

    assert isinstance(pred_dist, Empirical)
    assert pred_dist.time_indep is False
    assert pred_dist.spl.index.names == ["sample", "time"]
    assert pred_dist.spl.index.get_level_values("sample").nunique() == 9
    assert pred_dist.spl.index.get_level_values("time").unique().equals(pred_dist.index)
    assert pred_dist.spl.columns.equals(pred_dist.columns)


def test_toto_predict_proba_quantiles_match_direct_quantiles():
    """Toto's empirical quantiles agree with its direct quantile forecasts."""
    from skpro.distributions.empirical import Empirical

    y = load_airline()
    y_train = y.iloc[:-16]
    fh = np.arange(1, 4)
    alpha = [0.1, 0.33, 0.6, 0.9]
    forecaster = TotoForecaster(
        model_path="Datadog/Toto-Open-Base-1.0",
        device="cpu",
        seed=0,
        num_samples=9,
        samples_per_batch=9,
    ).fit(y_train, fh=fh)

    pred_dist = forecaster.predict_proba(fh=fh)
    pred_quantiles = forecaster.predict_quantiles(fh=fh, alpha=alpha)

    assert isinstance(pred_dist, Empirical)
    np.testing.assert_allclose(
        pred_dist.quantile(alpha).to_numpy(),
        pred_quantiles.to_numpy(),
        rtol=1e-5,
        atol=1e-4,
    )


def test_toto_predict_proba_mean_matches_mean_prediction():
    """Toto's empirical mean agrees with its mean point forecast."""
    y = load_airline()
    y_train = y.iloc[:-16]
    fh = np.arange(1, 4)
    forecaster = TotoForecaster(
        model_path="Datadog/Toto-Open-Base-1.0",
        device="cpu",
        seed=0,
        num_samples=9,
        samples_per_batch=9,
        prediction_type="mean",
    ).fit(y_train, fh=fh)

    pred_dist = forecaster.predict_proba(fh=fh)
    pred_mean = forecaster.predict(fh=fh)

    np.testing.assert_allclose(
        pred_dist.mean().to_numpy(),
        pred_mean.to_frame().to_numpy(),
        rtol=1e-5,
        atol=1e-4,
    )
