"""Regression tests for the LagLlama forecaster."""

import numpy as np
import pytest

from sktime.datasets import load_airline
from sktime.forecasting.lagllama import LagLlamaForecaster
from sktime.tests.test_switch import run_test_for_class

# Reference forecasts were generated by calling lag_llama.gluon.estimator's
# LagLlamaEstimator directly (checkpoint "time-series-foundation-models/Lag-Llama",
# revision 72dcfc29da106acfe38250a60f4ae29d1e56a3d9)
_LAGLLAMA_REFERENCE_CASES = [
    pytest.param(
        {"context_length": 32, "num_samples": 100},
        [549.983642578, 524.926696777, 503.950927734],
        id="context32-samples100",
    ),
    pytest.param(
        {"context_length": 64, "num_samples": 100, "use_rope_scaling": True},
        [558.188964844, 544.520446777, 539.267822266],
        id="context64-rope-scaling",
    ),
    pytest.param(
        {"context_length": 32, "num_samples": 20, "nonnegative_pred_samples": True},
        [560.322875977, 557.898803711, 538.202148438],
        id="context32-samples20-nonnegative",
    ),
]


@pytest.mark.skipif(
    not run_test_for_class(LagLlamaForecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)
@pytest.mark.parametrize(
    "forecaster_kwargs,expected_head",
    _LAGLLAMA_REFERENCE_CASES,
)
def test_lagllama_airline_predictions_match_source_reference(
    forecaster_kwargs, expected_head
):
    """LagLlama predictions match the original lag-llama package outputs."""
    y = load_airline()
    prediction_length = 16
    y_train = y.iloc[:-prediction_length]
    fh = np.arange(1, prediction_length + 1)
    forecaster = LagLlamaForecaster(
        **forecaster_kwargs,
        device="cpu",
    )

    y_pred = forecaster.fit(y_train, fh=fh).predict(fh=fh)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy(),
        np.asarray(expected_head, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )
