# copyright: sktime developers, BSD-3-Clause License (see LICENSE file)
"""Regression tests for the Mantis embedding-based forecaster."""

import numpy as np
import pytest

from sktime.datasets import load_airline
from sktime.forecasting.mantis import MantisForecaster
from sktime.tests.test_switch import run_test_for_class

# Reference forecasts were generated by calling mantis.architecture /
# mantis.trainer.MantisTrainer directly (rolling windows, resizing to the
# model's seq_len, embedding extraction, Ridge regression, recursive
# multi-step prediction), mirroring MantisForecaster's internal logic without
# importing sktime.
_MANTIS_REFERENCE_CASES = [
    pytest.param(
        "paris-noah/MantisV2",
        "v2",
        64,
        64,
        [386.9627685546875, 386.94677734375, 439.2170715332031],
        id="mantisv2-64-64-no-resize",
    ),
    pytest.param(
        "paris-noah/Mantis-8M",
        "v1",
        24,
        512,
        [393.2296142578125, 379.357177734375, 405.69122314453125],
        id="mantis8m-v1-24-512-upsampled",
    ),
]

pytestmark = pytest.mark.skipif(
    not run_test_for_class(MantisForecaster),
    reason="run test only if softdeps are present and incrementally (if requested)",
)


@pytest.mark.parametrize(
    "checkpoint,model_version,context_length,seq_len,expected_head",
    _MANTIS_REFERENCE_CASES,
)
def test_mantis_airline_predictions_match_source_reference(
    checkpoint, model_version, context_length, seq_len, expected_head
):
    """Mantis predictions match a direct mantis-tsfm reference implementation."""
    fh = np.arange(1, 13)
    y = load_airline()
    y_train = y.iloc[:-12]

    forecaster = MantisForecaster(
        checkpoint=checkpoint,
        model_version=model_version,
        context_length=context_length,
        seq_len=seq_len,
        device="cpu",
    )

    y_pred = forecaster.fit(y_train, fh=fh).predict(fh=fh)

    # Mantis's transformer backbone is not bitwise-reproducible across BLAS
    # backends (OpenBLAS/Linux, Accelerate/macOS, MKL/Windows), and the
    # recursive multi-step prediction compounds that float32 noise across
    # steps. Observed cross-platform deviations top out around 0.02 absolute
    # / 5e-5 relative on this reference case.
    # final values are calculated using:
    # 6 * sqrt(sum(x ** 2 for x in diffs) / len(diffs))
    # where diffs is the observed abs/rel difference across the runs in CI.
    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy(),
        np.asarray(expected_head, dtype=np.float32),
        rtol=2e-4,
        atol=8e-2,
    )
