"""Regression tests for the TinyTimeMixer forecaster."""

import numpy as np
import pytest

from sktime.datasets import load_airline
from sktime.forecasting.ttm import TinyTimeMixerForecaster
from sktime.utils.dependencies import _check_soft_dependencies

# Reference forecasts were generated by Granite-TSFM's end-to-end
# TimeSeriesPreprocessor and TimeSeriesForecastingPipeline at commit 743e709b.
# Checkpoint revisions below are immutable Hugging Face commit hashes.
_TTM_GRANITE_REFERENCE_CASES = [
    pytest.param(
        "ibm-granite/granite-timeseries-ttm-r1",
        "f04bebdd4c13475b006ce72672e74c9dc28871dc",  # main, 512-96-r1
        [
            529.254211426,
            506.502746582,
            496.432006836,
        ],
        id="r1-512-96-padded",
    ),
    pytest.param(
        "ibm-granite/granite-timeseries-ttm-r2",
        "d6a79570cac0f33d526601cd3a0fc7c80a8f9a2f",  # main, 512-96-r2
        [
            489.423187256,
            470.822448730,
            462.911132812,
        ],
        id="r2-512-96-padded",
    ),
    pytest.param(
        "ibm-granite/granite-timeseries-ttm-r2",
        "8c9c1d742ec5893d6419e3aa2ab21ed23e28df85",  # 52-16-ft-r2.1
        [
            503.695007324,
            494.769775391,
            487.770385742,
        ],
        id="r2-52-16-no-padding",
    ),
    pytest.param(
        "ibm-research/ttm-r3",
        "d1ee0cc20d857bee178b858c523999fc8680be4f",  # 52-16-dec-52-lite-r3
        [
            519.079772949,
            460.111022949,
            400.919677734,
        ],
        id="r3-52-16-no-padding",
    ),
    pytest.param(
        "ibm-research/ttm-r3",
        "60435cf7c03c3677e061fbe82150881f34de3607",  # 156-16-dec-52-lite-r3
        [
            492.963012695,
            434.377166748,
            383.149169922,
        ],
        id="r3-156-16-padded",
    ),
]


@pytest.mark.skipif(
    not _check_soft_dependencies(
        ["transformers", "torch", "accelerate>=0.26.0"], severity="none"
    ),
    reason="run test only if TinyTimeMixerForecaster soft dependencies are present",
)
@pytest.mark.parametrize(
    "model_path,checkpoint_commit,expected_head",
    _TTM_GRANITE_REFERENCE_CASES,
)
def test_ttm_airline_predictions_match_granite_reference(
    model_path, checkpoint_commit, expected_head
):
    """TTM predictions match the original Granite-TSFM pipeline outputs."""
    y = load_airline()
    y_train = y.iloc[:-16]
    fh = np.arange(1, 17)
    forecaster = TinyTimeMixerForecaster(
        model_path=model_path,
        revision=checkpoint_commit,
        fit_strategy="zero-shot",
        device="cpu",
        use_source_package=False,
    )

    y_pred = forecaster.fit(y_train, fh=fh).predict(fh=fh)

    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy(),
        np.asarray(expected_head, dtype=np.float32),
        rtol=1e-5,
        atol=1e-4,
    )
