"""Regression tests for the LagLlama forecaster."""

import numpy as np
import pytest
from skbase.utils.dependencies import _check_estimator_deps

from sktime.datasets import load_airline
from sktime.forecasting.lagllama import LagLlamaForecaster

# Reference forecasts were generated by calling lag_llama.gluon.estimator's
# LagLlamaEstimator directly (checkpoint "time-series-foundation-models/Lag-Llama",
# revision 72dcfc29da106acfe38250a60f4ae29d1e56a3d9)
_LAGLLAMA_REFERENCE_CASES = [
    pytest.param(
        {"context_length": 32, "num_samples": 100},
        [539.935913086, 518.222106934, 490.413940430],
        id="context32-samples100",
    ),
    pytest.param(
        {"context_length": 64, "num_samples": 100, "use_rope_scaling": True},
        [546.987243652, 534.520385742, 511.494567871],
        id="context64-rope-scaling",
    ),
    pytest.param(
        {"context_length": 32, "num_samples": 20, "nonnegative_pred_samples": True},
        [542.671142578, 540.072509766, 518.060302734],
        id="context32-samples20-nonnegative",
    ),
]


@pytest.mark.skipif(
    not _check_estimator_deps(LagLlamaForecaster, severity="none"),
    reason="run test only if LagLlamaForecaster soft dependencies are present",
)
@pytest.mark.parametrize(
    "forecaster_kwargs,expected_head",
    _LAGLLAMA_REFERENCE_CASES,
)
def test_lagllama_airline_predictions_match_source_reference(
    forecaster_kwargs, expected_head
):
    """LagLlama predictions match the original lag-llama package outputs."""
    y = load_airline()
    prediction_length = 16
    y_train = y.iloc[:-prediction_length]
    fh = np.arange(1, prediction_length + 1)
    forecaster = LagLlamaForecaster(
        **forecaster_kwargs,
        device="cpu",
    )

    y_pred = forecaster.fit(y_train, fh=fh).predict(fh=fh)

    # Unlike the other foundation forecasters covered by this style of test,
    # LagLlama's zero-shot forecast is a Monte Carlo mean over `num_samples`
    # paths drawn from a sampled StudentT distribution (via GluonTS's
    # `make_evaluation_predictions`), not a single deterministic forward pass.
    # PyTorch does not guarantee bit-identical floating point results for the
    # same seeded computation across different CPU hardware/backends (see
    # https://pytorch.org/docs/stable/notes/randomness.html), and here that
    # shows up as a few-percent drift in the sampled mean between machines
    # (observed up to ~5.4% on CI vs. the reference machine, shrinking with
    # larger `num_samples`, consistent with Monte Carlo noise rather than a
    # correctness bug -- vendored (`use_source_package=False`) and the real
    # `lag-llama` package (`use_source_package=True`) match bit-for-bit on a
    # single machine). `rtol` is therefore set well above that observed
    # cross-machine drift rather than at the tight tolerance used for the
    # deterministic foundation forecasters.
    np.testing.assert_allclose(
        y_pred.iloc[:3].to_numpy(),
        np.asarray(expected_head, dtype=np.float32),
        rtol=0.08,
    )
