"""Unit tests for all neural networks."""

from sktime.tests.test_all_estimators import BaseFixtureGenerator, QuickTester


class NetworkFixtureGenerator(BaseFixtureGenerator):
    """Fixture generator for classifier tests.

    Fixtures parameterized
    ----------------------
    object_class: estimator inheriting from BaseObject
        ranges over skbase classes not excluded by tests:skip_all/skip_by_name tags
    object_instance: instance of estimator inheriting from BaseObject
        ranges over skbase classes not excluded by tests:skip_all/skip_by_name tags
        instances are generated by create_test_instance class method
    scenario: instance of TestScenario
        ranges over all scenarios returned by retrieve_scenarios
    """

    # note: this should be separate from TestAllNetworks
    #   additional fixtures, parameters, etc should be added here
    #   TestAllNetworks should contain the tests only

    object_type_filter = "network"


class TestAllNetworks(NetworkFixtureGenerator, QuickTester):
    """Module level tests for all sktime neural networks."""

    def test_dummy(self, object_instance):
        """Dummy test to act as placeholder."""
        # check if multivariate input raises error for univariate regressors
        assert 42 == 42
