name: test specific sktime component
description: run unit tests on individual component of sktime framework
inputs:
  sktime-component-identifier:
    description: name of sktime component
    required: true
  python-version-identifier:
    description: python version to run tests
    required: true
runs:
  using: composite
  steps:
    - name: repository checkout step
      uses: actions/checkout@v4
    - name: python environment step
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version-identifier }}
    - name: dependencies installation step
      run: python3 -m pip install .[${{ inputs.sktime-component-identifier }},tests]
      shell: bash
    - name: unit test step
      run: python3 -m pytest sktime/${{ inputs.sktime-component-identifier }}
      shell: bash
    - name: test coverage step
      uses: codecov/codecov-action@v3
      with:
        flags: ${{ inputs.python-version-identifier }},${{ inputs.sktime-component-identifier }}
