name: "components unit tests"

inputs:
    sktime-component-identifier:
        description: "name of sktime component"
        required: true
    python-version-identifier:
        description: "python version"
        required: true
    sub-sample-estimators:
        description: "whether to test only subset of estimators"
        required: true
    test-affected-estimators:
        description: "whether to test only modified estimators"
        required: true

runs:
    using: "composite"
    steps:
    -
        name: "checkout repository"
        uses: "actions/checkout@v4"
        with:
            ref: "main"
            fetch-depth: 1
    -
        name: "set up python"
        uses: "actions/setup-python@v4"
        with:
            python-version: "${{ inputs.python-version-identifier }}"
    -
        name: "install dependencies"
        shell: "bash"
        run: |
            python3 -m pip install ".[${{ inputs.sktime-component-identifier }},tests]"
    -
        name: "run unit tests"
        shell: "bash"
        run: >-
            python3 -m pytest sktime/${{ inputs.sktime-component-identifier }}
            --matrixdesign ${{ inputs.sub-sample-estimators }}
            --only_changed_modules ${{ inputs.test-affected-estimators }}
    -
        name: "send coverage to codecov"
        uses: "codecov/codecov-action@v3"
        with:
            flags: "${{ inputs.python-version-identifier }},${{ inputs.sktime-component-identifier }}"
