name: Build Wheels and Push to PyPI

on:
  # TODO: uncomment the release trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # release:
  #   types: [published]


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: cp36-* pp* *-manylinux_i686 *-musllinux_i686 *-musllinux_x86_64
          # CIBW_TEST_REQUIRES: pytest pytest-cov pytest-xdist
          CIBW_TEST_EXTRAS: "all_extras,dev"
          CIBW_TEST_COMMAND: pytest --showlocals --durations=20 -n 2 --pyargs sktime
        # run: python -m cibuildwheel --output-dir wheelhouse
        run: bash build_tools/github/build_wheels.sh

      - name: Store wheels
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

  # Build the source distribution under Linux
  build_sdist:
    name: Source distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build source distribution
        run: |
          python -m pip install build
          python -m build --sdist --outdir wheelhouse

      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.tar.gz

      # - name: Publish package to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     user: ${{ secrets.PYPI_USERNAME }}
      #     password: ${{ secrets.PYPI_PASSWORD }}
      #     packages_dir: wheelhouse/
