name: Cancel Workflows on Push
on:
  workflow_run:
    workflows: ["Install and test"]
    types:
      - requested
jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.12.1
      with:
        workflow_id: ${{ github.event.workflow.id }}
