name: Auto-Label PRs by Size
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '10'
          s_label: 'size/S'
          s_max_size: '50'
          m_label: 'size/M'
          m_max_size: '100'
          l_label: 'size/L'
          l_max_size: '500'
          xl_label: 'size/XL'
