name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  code_quality:
    name: code quality
    runs-on: ubuntu-latest
    steps:
      - name: repository checkout step
        uses: actions/checkout@v4
      - name: python environment step
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: install pre-commit
        run: python3 -m pip install pre-commit
      - id: changed-files
        name: identify modified files
        uses: tj-actions/changed-files@v42
      - name: run pre-commit hooks on modified files
        run: pre-commit run --color always --files ${{ steps.changed-files.outputs.all_changed_files }} --show-diff-on-failure
      - name: check missing __init__ files
        run: build_tools/fail_on_missing_init_files.sh
        shell: bash
  detect:
    needs: code_quality
    name: detect changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      datasets: ${{ steps.filter.outputs.datasets }}
      pyproject: ${{ steps.filter.outputs.pyproject }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            datasets:
              - sktime/base/**
              - sktime/datasets/**
            pyproject:
              - pyproject.toml
  test:
    needs: detect
    name: install
    if: ${{ needs.detect.outputs.pyproject == 'true' }}
    uses: ./.github/workflows/test_install.yml
  unit_test_base:
    needs: code_quality
    name: base
    uses: ./.github/workflows/test_base.yml
  unit_test_module:
    needs: code_quality
    name: module
    uses: ./.github/workflows/test_module.yml
  unit_test_other:
    needs: code_quality
    name: other
    uses: ./.github/workflows/test_other.yml
  unit_test_datasets:
    needs: detect
    name: datasets
    if: ${{ needs.detect.outputs.datasets == 'true' }}
    uses: ./.github/workflows/test_datasets.yml
