name: test softdep set install
on:
  schedule:
    - cron: 0 0 1 * *
  workflow_call:
  workflow_dispatch:
jobs:
  test_installations:
    name: install
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        operating-system:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        sktime-extra:
          - all_extras_pandas2
          - alignment
          - annotation
          - classification
          - clustering
          - forecasting
          - networks
          - param_est
          - regression
          - transformations
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: checkout pull request branch
        uses: actions/checkout@v4
      - name: install ${{ matrix.sktime-extra }} extra on python ${{ matrix.python-version }}
        uses: ./.github/actions/test-install
        with:
          sktime-extra-identifier: ${{ matrix.sktime-extra }}
          python-version-identifier: ${{ matrix.python-version }}
