name: test components with extras
on:
  workflow_call:
jobs:
  detect:
    name: detect changes in components with extras
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      components_with_extras: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            alignment:
              - sktime/base/**
              - sktime/alignment/**
            annotation:
              - sktime/base/**
              - sktime/annotation/**
            classification:
              - sktime/base/**
              - sktime/classification/**
            clustering:
              - sktime/base/**
              - sktime/clustering/**
            forecasting:
              - sktime/base/**
              - sktime/forecasting/**
            networks:
              - sktime/base/**
              - sktime/networks/**
            param_est:
              - sktime/base/**
              - sktime/param_est/**
            regression:
              - sktime/base/**
              - sktime/regression/**
            transformations:
              - sktime/base/**
              - sktime/transformations/**
  test:
    needs: detect
    name: test components with extras
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        operating-system:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        sktime-component: ${{ fromJSON(needs.detect.outputs.components_with_extras) }}
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: checkout pull request branch
        uses: actions/checkout@v4
      - name: run tests for component ${{ matrix.sktime-component }} on python ${{ matrix.python-version }}
        uses: ./.github/actions/test-component
        with:
          sktime-component-identifier: ${{ matrix.sktime-component }}
          python-version-identifier: ${{ matrix.python-version }}
          sub-sample-estimators: "True"
          test-affected-estimators: "True"
      - name: upload coverage
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.operating-system }},${{ matrix.python-version }},${{ matrix.sktime-component }},incomplete
